import {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
  // title: "page-title - Next.js-14" //title can be a String

  // Or title can be defined as Object, which have 3 options ---
  title: {
    default: "Lrn - Next.js-14", // Default title, applied in those pages where title is not defined in page.tsx/layout.tsx
    template: "%s | N_Ah", // from pages 'metadata'
    absolute: "" // Absolute will ignore all other, this string will show, thats why its better to put absolute in specific pages only.
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "lightblue", padding: "1rem" }}>
          <Link href="/">Home</Link>
        </header>
        {children}
        <footer style={{ background: "ghostwhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  )
}
